const DISCORD_URL = 'https://discord.gg/qUWUjSndMW';

const RANKS = [
  {
    id: 'sentinel',
    name: 'Sentinel',
    price: 2.99,
    badge: 'assets/sentinel.webp',
    accent: '#a8b2c0',
    accentGlow: 'rgba(168, 178, 192, 0.35)',
    perks: [
      '5 Homes',
      '15 Auction listings',
      '7 Order queues',
      'Sentinel streak rewards & kit',
      '/craft /anvil',
      '2 Weekly {Placeholder} Crate Keys',
      'Priority queue',
      'Crate quick open',
    ],
  },
  {
    id: 'crusader',
    name: 'Crusader',
    price: 5.99,
    badge: 'assets/crusader.webp',
    accent: '#3ecf6e',
    accentGlow: 'rgba(62, 207, 110, 0.35)',
    perks: [
      '7 Homes',
      'No chat cooldown',
      '20 Auction listings',
      '10 Order queues',
      'Crusader streak rewards & kit',
      '/craft /anvil /ec (+1 row)',
      'Auction insta-buy',
      'Monthly streak saver',
      '4 Weekly {Placeholder} Crate Keys',
      'Priority queue',
      'Crate quick open',
    ],
  },
  {
    id: 'champion',
    name: 'Champion',
    price: 9.99,
    badge: 'assets/champion.webp',
    accent: '#f0c040',
    accentGlow: 'rgba(240, 192, 64, 0.35)',
    perks: [
      '9 Homes',
      'No chat cooldown',
      '25 Auction listings',
      '12 Order queues',
      'Champion streak rewards & kit',
      'Custom name color',
      '/nickname /craft /anvil /ec (+2 rows)',
      'Auction insta-buy',
      'Monthly streak saver',
      '6 Weekly {Placeholder} Crate Keys',
      'Priority queue',
      'Crate quick open',
    ],
  },
  {
    id: 'ascendant',
    name: 'Ascendant',
    price: 13.99,
    badge: 'assets/ascendant.webp',
    accent: '#9333ea',
    accentGlow: 'rgba(147, 51, 234, 0.35)',
    perks: [
      '12 Homes',
      'No chat cooldown',
      '30 Auction listings',
      '15 Order queues',
      'Ascendant streak rewards & kit',
      'Custom name color',
      '/nickname /craft /anvil /ec (6-row ender chest)',
      'Auction insta-buy',
      'Bi-weekly streak saver',
      '8 Weekly {Placeholder} Crate Keys',
      'Priority queue',
      'Crate quick open',
    ],
  },
  {
    id: 'immortal',
    name: 'Immortal',
    price: 19.99,
    badge: 'assets/immortal.webp',
    accent: '#22d3ee',
    accentGlow: 'rgba(34, 211, 238, 0.4)',
    perks: [
      '14 Homes',
      'No chat cooldown',
      '40 Auction listings',
      '20 Order queues',
      'Immortal streak rewards & kit',
      'Custom name color',
      '/nickname /craft /anvil /ec (8-row ender chest)',
      'Auction insta-buy',
      'Weekly streak saver',
      '10 Weekly {Placeholder} Crate Keys',
      'Priority queue',
      'Crate quick open',
    ],
  },
];

const COMPARISON_ROWS = [
  { label: 'Homes', values: ['5', '7', '9', '12', '14'] },
  { label: 'Auction Listings', values: ['15', '20', '25', '30', '40'] },
  { label: 'Order Queues', values: ['7', '10', '12', '15', '20'] },
  { label: 'Chat Cooldown', values: ['Yes', 'None', 'None', 'None', 'None'] },
  { label: 'Streak Rewards & Kit', values: ['Sentinel', 'Crusader', 'Champion', 'Ascendant', 'Immortal'] },
  { label: 'Weekly {Placeholder} Crate Keys', values: ['2', '4', '6', '8', '10'] },
  { label: 'Ender Chest', values: ['—', '+1 row', '+2 rows', '6 rows', '8 rows'] },
  { label: 'Streak Saver', values: ['—', 'Monthly', 'Monthly', 'Bi-weekly', 'Weekly'] },
  { label: 'Auction Insta-buy', values: ['—', '✓', '✓', '✓', '✓'] },
  { label: 'Custom Name Color', values: ['—', '—', '✓', '✓', '✓'] },
  { label: 'Priority Queue', values: ['✓', '✓', '✓', '✓', '✓'] },
  { label: 'Crate Quick Open', values: ['✓', '✓', '✓', '✓', '✓'] },
];

const KIT_PERKS = [
  { label: '/craft', values: [true, true, true, true, true] },
  { label: '/anvil', values: [true, true, true, true, true] },
  { label: '/ec', values: [false, true, true, true, true] },
  { label: '/nickname', values: [false, false, true, true, true] },
  { label: 'No Chat Cooldown', values: [false, true, true, true, true] },
  { label: 'Auction Insta-buy', values: [false, true, true, true, true] },
  { label: 'Streak Saver', values: [false, true, true, true, true] },
  { label: 'Priority Queue', values: [true, true, true, true, true] },
  { label: 'Crate Quick Open', values: [true, true, true, true, true] },
];

const HOME_FEATURES = [
  { icon: '⚔', title: 'Earn Ranks Through Gameplay', text: 'Progress by grinding money and kills — no wallet required to reach the top.' },
  { icon: '🏆', title: 'Competitive Leaderboards', text: 'Kills, Money, Playtime, and Streaks — prove you belong at the top.' },
  { icon: '🔥', title: 'Daily Streak Rewards', text: 'Show up, stack streaks, and unlock escalating kit rewards.' },
  { icon: '⏱', title: 'Playtime Milestones', text: 'Time on the server pays off with milestone rewards as you grind.' },
  { icon: '💰', title: 'Player-Driven Economy', text: 'Shops, auctions, and orders — the market is yours to shape.' },
  { icon: '🗡', title: 'Competitive PvP (The Pit)', text: 'Drop into The Pit and test your skill against other players.' },
];

const MC_USERNAME_RE = /^[A-Za-z0-9_]{3,16}$/;
