const DISCORD_URL = 'https://discord.gg/qUWUjSndMW';
const SUPPORT_DISCORD_URL = 'https://discord.gg/93D5Jt8jEr';
const CONTACT_EMAIL = 'SpearMaceSMP@gmail.com';
const IP_PLACEHOLDER = '{Placeholder}';

const RANKS = [
  {
    id: 'immortal',
    name: 'Immortal',
    badge: 'assets/immortal.webp',
    accent: '#22d3ee',
    accentGlow: 'rgba(34, 211, 238, 0.4)',
    lifetimePrice: 19.99,
    monthlyPrice: 3.99,
    monthlyNote: '$5.99 after first month',
    bestDeal: true,
    perks: [
      '14 Homes',
      'No chat cooldown',
      '40 Auction listings',
      '20 Order queues',
      'Immortal streak rewards',
      'Immortal kit',
      'Custom name color',
      '/nickname',
      '/craft',
      '/anvil',
      '/ec',
      '8 Row ender chest',
      'Auction insta buy',
      'Weekly streak saver',
      '10 Weekly {Placeholder} crate keys',
      'Priority queue',
      'Crate quick open',
    ],
  },
  {
    id: 'ascendant',
    name: 'Ascendant',
    badge: 'assets/ascendant.webp',
    accent: '#9333ea',
    accentGlow: 'rgba(147, 51, 234, 0.35)',
    lifetimePrice: 13.99,
    monthlyPrice: 4.99,
    monthlyNote: null,
    bestDeal: false,
    perks: [
      '12 Homes',
      'No chat cooldown',
      '30 Auction listings',
      '15 Order queues',
      'Ascendant streak rewards',
      'Ascendant kit',
      'Custom name color',
      '/nickname',
      '/craft',
      '/anvil',
      '/ec',
      'Double chest size ender chest (6 rows)',
      'Auction insta buy',
      'Bi-Weekly streak saver',
      '8 Weekly {Placeholder} crate keys',
      'Priority queue',
      'Crate quick open',
    ],
  },
  {
    id: 'champion',
    name: 'Champion',
    badge: 'assets/champion.webp',
    accent: '#f0c040',
    accentGlow: 'rgba(240, 192, 64, 0.35)',
    lifetimePrice: 9.99,
    monthlyPrice: 3.99,
    monthlyNote: null,
    bestDeal: false,
    perks: [
      '9 Homes',
      'No chat cooldown',
      '25 Auction listings',
      '12 Order queues',
      'Champion streak rewards',
      'Champion kit',
      'Custom name color',
      '/nickname',
      '/craft',
      '/anvil',
      '/ec',
      '+ 2 Rows in ender chest',
      'Auction insta buy',
      'Monthly streak saver',
      '6 Weekly {Placeholder} crate keys',
      'Priority queue',
      'Crate quick open',
    ],
  },
  {
    id: 'crusader',
    name: 'Crusader',
    badge: 'assets/crusader.webp',
    accent: '#3ecf6e',
    accentGlow: 'rgba(62, 207, 110, 0.35)',
    lifetimePrice: 5.99,
    monthlyPrice: null,
    monthlyNote: null,
    bestDeal: false,
    perks: [
      '7 Homes',
      'No chat cooldown',
      '20 Auction listings',
      '10 Order queues',
      'Crusader streak rewards',
      'Crusader kit',
      '/craft',
      '/anvil',
      '/ec',
      '+ 1 Row in ender chest',
      'Auction insta buy',
      'Monthly streak saver',
      '4 Weekly {Placeholder} crate keys',
      'Priority queue',
      'Crate quick open',
    ],
  },
  {
    id: 'sentinel',
    name: 'Sentinel',
    badge: 'assets/sentinel.webp',
    accent: '#a8b2c0',
    accentGlow: 'rgba(168, 178, 192, 0.35)',
    lifetimePrice: 2.99,
    monthlyPrice: null,
    monthlyNote: null,
    bestDeal: false,
    perks: [
      '5 Homes',
      '15 Auction listings',
      '7 Order queues',
      'Sentinel streak rewards',
      'Sentinel kit',
      '/craft',
      '/anvil',
      '2 Weekly {Placeholder} crate keys',
      'Priority queue',
      'Crate quick open',
    ],
  },
];

const COMPARISON_ROWS = [
  { label: 'Homes', values: ['14', '12', '9', '7', '5'] },
  { label: 'Auction Listings', values: ['40', '30', '25', '20', '15'] },
  { label: 'Order Queues', values: ['20', '15', '12', '10', '7'] },
  { label: 'Chat Cooldown', values: ['None', 'None', 'None', 'None', 'Yes'] },
  { label: 'Streak Rewards & Kit', values: ['Immortal', 'Ascendant', 'Champion', 'Crusader', 'Sentinel'] },
  { label: 'Weekly {Placeholder} Crate Keys', values: ['10', '8', '6', '4', '2'] },
  { label: 'Ender Chest', values: ['8 rows', '6 rows', '+2 rows', '+1 row', '—'] },
  { label: 'Streak Saver', values: ['Weekly', 'Bi-weekly', 'Monthly', 'Monthly', '—'] },
  { label: 'Auction Insta-buy', values: ['✓', '✓', '✓', '✓', '—'] },
  { label: 'Custom Name Color', values: ['✓', '✓', '✓', '—', '—'] },
  { label: 'Priority Queue', values: ['✓', '✓', '✓', '✓', '✓'] },
  { label: 'Crate Quick Open', values: ['✓', '✓', '✓', '✓', '✓'] },
];

const KIT_PERKS = [
  { label: '/craft', values: [true, true, true, true, true] },
  { label: '/anvil', values: [true, true, true, true, true] },
  { label: '/ec', values: [true, true, true, true, false] },
  { label: '/nickname', values: [true, true, true, false, false] },
  { label: 'No Chat Cooldown', values: [true, true, true, true, false] },
  { label: 'Auction Insta-buy', values: [true, true, true, true, false] },
  { label: 'Streak Saver', values: [true, true, true, true, false] },
  { label: 'Priority Queue', values: [true, true, true, true, true] },
  { label: 'Crate Quick Open', values: [true, true, true, true, true] },
];

const HOME_FEATURES = [
  { icon: '⚔', title: 'Earn Ranks Through Gameplay', text: 'Grind money and kills to rank up. You do not need to spend money to climb.' },
  { icon: '🏆', title: 'Competitive Leaderboards', text: 'Track kills, money, playtime, and streaks. See where you stand.' },
  { icon: '🔥', title: 'Daily Streak Rewards', text: 'Log in, keep your streak, and pick up better kit rewards as it grows.' },
  { icon: '⏱', title: 'Playtime Milestones', text: 'The longer you play, the more milestone rewards you unlock.' },
  { icon: '💰', title: 'Player-Driven Economy', text: 'Run shops, list auctions, fill orders. The market moves because players move it.' },
  { icon: '🗡', title: 'Competitive PvP (The Pit)', text: 'Fight in The Pit when you want raw PvP without the usual survival overhead.' },
];

const CRATE_SLOTS = 6;
const BUNDLE_SLOTS = 5;

const STORE_CATEGORIES = ['ranks', 'keys', 'bundles'];

const MC_USERNAME_RE = /^[A-Za-z0-9_]{3,16}$/;
